// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXr3uyTrsxzN4UMIptCYuiGsHmkgj6MU',
    appId: '1:268171989644:web:8288c1d7e35846c54be1a9',
    messagingSenderId: '268171989644',
    projectId: 'face-70344',
    authDomain: 'face-70344.firebaseapp.com',
    databaseURL: 'https://face-70344-default-rtdb.firebaseio.com',
    storageBucket: 'face-70344.firebasestorage.app',
    measurementId: 'G-0KYDZ0R9X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPwr3lp9ISz1rLI4k-vE6-_S9vLwPP_I',
    appId: '1:268171989644:android:95bc6698bc3bacae4be1a9',
    messagingSenderId: '268171989644',
    projectId: 'face-70344',
    databaseURL: 'https://face-70344-default-rtdb.firebaseio.com',
    storageBucket: 'face-70344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqPQKdCHPp4FJvurXGZwPeTpKqeKMwNE',
    appId: '1:268171989644:ios:04e76544648f6f654be1a9',
    messagingSenderId: '268171989644',
    projectId: 'face-70344',
    databaseURL: 'https://face-70344-default-rtdb.firebaseio.com',
    storageBucket: 'face-70344.firebasestorage.app',
    androidClientId: '268171989644-1qle0a7nfjlrb64d4hh89nb9t2vb2u0o.apps.googleusercontent.com',
    iosClientId: '268171989644-26qfl981nt1mdj4nn68m2cm1hptps0kq.apps.googleusercontent.com',
    iosBundleId: 'com.asas.engineers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqPQKdCHPp4FJvurXGZwPeTpKqeKMwNE',
    appId: '1:268171989644:ios:58d8c261ff5982234be1a9',
    messagingSenderId: '268171989644',
    projectId: 'face-70344',
    databaseURL: 'https://face-70344-default-rtdb.firebaseio.com',
    storageBucket: 'face-70344.firebasestorage.app',
    androidClientId: '268171989644-1qle0a7nfjlrb64d4hh89nb9t2vb2u0o.apps.googleusercontent.com',
    iosClientId: '268171989644-nktjekg690p68395u2v7v0gdvuk2sa9s.apps.googleusercontent.com',
    iosBundleId: 'com.asas.engineers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHFpwuRbhiscovGleH2uFvSZTVNXEviZU',
    appId: '1:268171989644:web:d48a5798aa18dec04be1a9',
    messagingSenderId: '268171989644',
    projectId: 'face-70344',
    authDomain: 'face-70344.firebaseapp.com',
    databaseURL: 'https://face-70344-default-rtdb.firebaseio.com',
    storageBucket: 'face-70344.firebasestorage.app',
    measurementId: 'G-ZWE17Y474M',
  );
}